# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11.7
exclude: '.cache|.git|.tox'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
        files: .*\.*.py
    -   id: trailing-whitespace
        files: .*\.*.py
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: debug-statements

# -   repo: https://github.com/psf/black
#     rev: 23.11.0
#     hooks:
#     -   id: black
#         args: ['--check', '--diff', '--color', '-l', '100']

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: pipx run black
        language: python
        language_version: python3.11
        types: [python]
        args: ['--check', '--diff', '--color', '-l', '100']

# -   repo: https://github.com/timothycrosley/isort
#     rev: 5.13.0
#     hooks:
#     -   id: isort
#         args: ["--profile", "black", "--filter-files", "--skip-gitignore"]

-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: pipx run isort
        language: python
        args: ["--profile", "black", "--filter-files", "--skip-gitignore"]