# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
    # It is recommended to specify the latest version of Python
    # supported by your project here, or alternatively use
    # pre-commit's default_language_version, see
    # https://pre-commit.com/#top_level-default_language_version

-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files", "-l 100", "--skip-gitignore"]
